### PR TITLE
added gh-actions file

### PR DESCRIPTION
**Pull request by himorin**

### CODE REVIEW

**Review by nigelmegitt — APPROVED** [review]
I can't actually confirm if this works or not, but happy for you to merge and test @himorin . Thank you!

**Comment by himorin** [comment]
actually, I need real test to verify, since there are some required additional repository configuration.

**Comment by nigelmegitt** [comment]
Looks like it ran, at https://github.com/w3c/imsc-hrm/runs/4415694717?check_suite_focus=true but some steps were skipped, without any obvious explanation. Is it worth re-running?

**Comment by himorin** [comment]
This GHActions tracks only spec file and its associated figures, so updates on other than them will make actions to skip some items. (so, correctly working for this kind of PR)

**Pull request merged**
