### PR TITLE
REC publication

### LINKED ISSUE #79: A few minor editorial suggestions
I've just been reviewing the spec and have a few minor suggestions:

1. The Abstract currently talks more about what the spec doesn't do, and I think could explain more about what it does do. I suggest including some of the text from 5.1 Objective.
2. In the Abstract and Scope sections, I think "an Hypothetical" should be "a Hypothetical", as the H is pronounced.
3. In Figure 1 "all IMSC instance document" should be "all IMSC instance documents".
4. In section 6, "sequence of Intermediate Synchronic Documents" is referred to as Ei, but in section 7 it's referred to as En. Should these be the same in both sections?

### PR DESCRIPTION
**Pull request by palemieux**
Closes #79

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc-hrm/pull/80.html" title="Last updated on Apr 25, 2024, 2:55 PM UTC (6d09944)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc-hrm/80/10624aa...6d09944.html" title="Last updated on Apr 25, 2024, 2:55 PM UTC (6d09944)">Diff</a>

### CODE REVIEW

**Comment by palemieux** [comment]
@ashimura What will the errata URL be for the document? respec expects it.

**Comment by himorin** [comment]
> `https://www.w3.org/2024/04/imsc-hrm-errata.html`

draft uploaded. please let me know if you find anything to be fixed @palemieux @nigelmegitt

**Review by chrisn — APPROVED** [review]
Looks good, thank you! And many congrats on getting this to Rec.

**Review by nigelmegitt — APPROVED** [review]
Looks good to me.

Respec is doing something a bit weird with the Errata link, which just reads "Errata exists". Comparing with [IMSC 1.2](https://www.w3.org/TR/ttml-imsc1.2/), which says

>Please check the [errata](https://www.w3.org/2020/08/ttml-imsc1.2-errata.html) for any errors or issues reported since publication.

I prefer the friendly sentence of IMSC1.2. Not sure if that's actually something we can control though.

**Comment by palemieux** [comment]
> I prefer the friendly sentence of IMSC1.2. Not sure if that's actually something we can control though.

There is an outstanding issue: https://github.com/w3c/respec/issues/4446

**Comment by himorin** [comment]
@nigelmegitt @palemieux so, it's ok to go with this now?? (e.g. REC transition request)

**Comment by nigelmegitt** [comment]
@himorin yes, I think you can merge this and use as the basis of a REC transition request.

**Comment by nigelmegitt** [comment]
This now published as Rec at https://www.w3.org/TR/2024/REC-imsc-hrm-20240425/ - suggest merging.

**Pull request merged**
