### PR TITLE
Define IMSC acronym

### LINKED ISSUE #26: expand IMSC acronym
As a style thing, please expand the IMSC acronym in the abstract (at least) and possibly also in a new introduction section.

### PR DESCRIPTION
**Pull request by palemieux**
Closes #26

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc-hrm/pull/32.html" title="Last updated on Feb 1, 2022, 5:03 AM UTC (b0455ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc-hrm/32/19f71e9...b0455ba.html" title="Last updated on Feb 1, 2022, 5:03 AM UTC (b0455ba)">Diff</a>

### CODE REVIEW

**Review by nigelmegitt — COMMENTED** [review]
Is it worth changing all instances of "IMSC" in the document to be references? I found these places:

* The note in §9
* 2nd paragraph in §B.1
* B2 (two places)

**Comment by himorin** [comment]
Three `IMSC Document` in section B is ok without `Instance`? (just a question...)

**Comment by nigelmegitt** [comment]
> Three `IMSC Document` in section B is ok without `Instance`? (just a question...)

I think those got fixed in ef0a01c - please could you check again the latest on this PR @himorin ?

**Comment by himorin** [comment]
> > Three `IMSC Document` in section B is ok without `Instance`? (just a question...)
> 
> I think those got fixed in [ef0a01c](https://github.com/w3c/imsc-hrm/commit/ef0a01c55708b0021b9ed6ab8dcbc175512b9549) - please could you check again the latest on this PR @himorin ?

Ah yes! thank you for pointing. I thought I've seen at somewhere but I could not find in this PR, so I wrongly considered I've seen a phantom...

**Pull request merged**
